version: "3.5"

services:
  blog:
    build:
      context: ./
    ports:
      - 80:4000
    volumes:
      - .:/usr/src/app
    stdin_open: true
    tty: true
    container_name: site-life
    command: bundle exec jekyll serve -H 0.0.0.0 -t
