version: "3.5"

services:

  site:
    build:
      context: ./docker/jekyll
      dockerfile: Dockerfile
    ports:
      - 80:4000
    volumes:
      - .:/usr/src/app
    stdin_open: true
    tty: true
    container_name: site-life
    command: bundle exec jekyll serve -H 0.0.0.0 -t

  webhooker:
    build:
      context: ./docker/webhooker
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
    stdin_open: true
    tty: true
    container_name: webhooker-life    
    entrypoint: ["bash", "-c", "git config --global --add safe.directory /usr/src/app && uvicorn webhooker:app --host 0.0.0.0 --port 8000"] 
